name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --check-cache

      - name: Run Prettier
        run: yarn prettier

      - name: Run Stylelint
        run: yarn stylelint

      - name: Run EsLint
        run: yarn lint

      - name: Run the tests
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Build
        run: yarn build && yarn workspace website build

      - name: Archive production
        uses: actions/upload-artifact@v3
        with:
          name: lib
          path: ./lib

      - name: Generate API Documentation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: generate API from TypeDoc'
          add_options: '--force'
          file_pattern: 'website/docs/api'
