name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --check-cache

      - name: Run Prettier
        run: yarn prettier

      - name: Run Stylelint
        run: yarn stylelint

      - name: Run EsLint
        run: yarn lint

      - name: Run the tests
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        run: yarn build && yarn workspace website build

      - name: Archive production
        uses: actions/upload-artifact@v4
        with:
          name: lib
          path: ./lib

      - name: Generate API Documentation
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: generate API from TypeDoc'
          add_options: '-f'
          disable_globbing: true
          commit_options: --allow-empty
          file_pattern: 'website/docs/api'
          skip_dirty_check: true
