name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: yarn install --check-cache
      - run: yarn prettier
      - run: yarn stylelint
      - run: yarn lint
      - run: yarn test
  publish-npm:
    needs: gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: https://registry.npmjs.org/
      - run: yarn install --check-cache
      - run: yarn config set npmAuthToken ${{secrets.NPM_TOKEN}}
      - run: yarn build
      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  release-tag:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  gh-pages:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Build Demo Website
        run: |
          yarn install --check-cache
          yarn workspace example build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: example/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
